version: "3"
services:
  vzug:
    container_name: vzug
    image: vzug
    working_dir: /code
    volumes:
      - .:/code
    command: python3 poll.py
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "5"
